# Generated by Django 5.1.3 on 2025-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=11)),
                ('month', models.CharField(max_length=11)),
                ('experience', models.CharField(max_length=11)),
            ],
        ),
    ]
