# Generated by Django 5.1.3 on 2025-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0002_feedback_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='experience',
            field=models.CharField(choices=[('4', 'Very Satisfied'), ('3', 'Satisfied'), ('2', 'Unsatisfied'), ('1', 'Very Unsatisfied')], default='Satisfied', max_length=20),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
