# Generated by Django 5.1.3 on 2025-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0003_alter_feedback_experience_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
