# Generated by Django 5.1.3 on 2025-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0004_alter_feedback_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Olive',
        ),
    ]
