# Generated by Django 5.1.3 on 2025-02-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0005_rename_feedback_olive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Olive',
            new_name='Feedback',
        ),
    ]
