# Generated by Django 5.1.3 on 2025-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0006_rename_olive_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='experience',
            field=models.CharField(choices=[('4', 'Very Satisfied'), ('3', 'Satisfied'), ('2', 'Unsatisfied'), ('1', 'Very Unsatisfied')], default='3', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=6),
        ),
    ]
