# Generated by Django 5.1.3 on 2025-02-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0007_alter_feedback_experience_alter_feedback_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
