# Generated by Django 5.1.3 on 2025-02-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morning', '0008_alter_feedback_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Data',
        ),
    ]
